name: COES Alert
on:
  schedule:
    - cron: "*/30 * * * *"   # cada 30 min (UTC)
  workflow_dispatch:

permissions:
  contents: read
concurrency:
  group: coes-alert
  cancel-in-progress: true

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Cache pip
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          python -m playwright install --with-deps

      - name: Run alert (one-shot)
        env:
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID:   ${{ secrets.TELEGRAM_CHAT_ID }}
          UMBRAL_S_POR_MWH:   "0"
          INTERVALO_MINUTOS:  "30"
          BARRA_BUSCADA:      "CHICLAYO 220"
          ONESHOT:            "1"
          # Persistencia opcional en Gist (recomendado)
          GIST_TOKEN: ${{ secrets.GIST_TOKEN }}
          GIST_ID:    ${{ secrets.GIST_ID }}
          GIST_FILENAME: "estado_alerta_chiclayo220.json"
        run: |
          python alerta_costo_marginal_chiclayo_telegram.py
      
      - name: Upload debug artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: coes-debug
          path: |
            export_debug.xlsx
            html_main.html
            frame_*.html
            page_after_buscar.png
          if-no-files-found: ignore
  
